# Generated by Django 3.1.2 on 2022-07-04 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPSDataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(blank=True, default=0.0)),
                ('lng', models.FloatField(blank=True, default=0.0)),
                ('bearing', models.IntegerField(blank=True, default=0)),
                ('velocity', models.FloatField(blank=True, default=0.0)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
