# Generated by Django 3.1.2 on 2022-07-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0002_gpssettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpsdatapoint',
            name='useForCalculation',
            field=models.BooleanField(default=True),
        ),
    ]
