# Generated by Django 3.1.2 on 2022-07-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0003_gpsdatapoint_useforcalculation'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPSWayPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(blank=True, default=0.0)),
                ('lng', models.FloatField(blank=True, default=0.0)),
                ('bearing', models.IntegerField(blank=True, default=0)),
                ('velocity', models.FloatField(blank=True, default=0.0)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('useForCalculation', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Inget namn', max_length=127)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('waypoints', models.ManyToManyField(default=None, to='gps.GPSWayPoint')),
            ],
        ),
    ]
